version: '3'
silent: true
tasks:
  get:
    desc: "️⛓️ Get dependencies"
    cmds:
      - fvm dart pub get

  run:
    desc: "🚀 Run Dart app"
    cmds:
      - fvm dart run bin/either.dart

  default:
    cmds:
      - task -l --sort none